### ISSUE TITLE
Cant unpack NRC arhive

### ISSUE THREAD

**Issue by avevitaliy** [dbachilo/nrc#1]
Error when unpack NRC arhive
```
# tar xfvz NRC.tar.gz 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

```

**Comment by dbachilo** [comment]
Just downloaded it myself from here and successfully unpacked it using your command. Your browser probably just failed to download it properly. Anyway that is a source archive, in most cases you don't need it.
